name: build

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Checking Out Repository
      uses: actions/checkout@v2
    - run:
        name: Set BASH_ENV
        command: |
          echo "set -e" >> $BASH_ENV
          echo "export DISPLAY=:99" >> $BASH_ENV
          echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV
          echo "BASH_ENV:"
          cat $BASH_ENV
    - run:
        name: Install pip
        command: |
          python -m pip install --user --upgrade --progress-bar off pip
    - run:
        name: Install requirements
        command: |
          python -m pip install --user --upgrade --progress-bar off -r requirements.txt
          python -m pip install --user --upgrade --progress-bar off -r doc/doc-requirements.txt
    - run:
        name: Install package
        command: |
          python -m pip install --user -e .
    # Look at what we have and fail early if there is some library conflict
    - run:
        name: Check installation
        command: |
          which python
          python -c "import momentumnet"
    # Build docs
    - run:
        name: make html
        no_output_timeout: 30m
        command: |
          cd doc;
          make clean;
          make html;
          cd ..;
    # Deploy docs
    - name: Deploy to Github Pages if on Master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: michaelsdr/michaelsdr.github.io
        destination_dir: main
        publish_branch: main
        publish_dir: ./docs/_build/html
        cname: michaelsdr.github.io/momentumnet
